### ISSUE TITLE
Text colors don't match the pdf file - blue/red is switched

### ISSUE THREAD

**Issue by lukaspacha** [vfr/UXReader-iOS#12]
Didn't had the time to figure out why, but there seems to be a problem with text colors / blue-red is switched somehow. 

[colors.pdf](https://github.com/vfr/UXReader-iOS/files/1491870/colors.pdf)
![img_0238](https://user-images.githubusercontent.com/793494/33080172-bf047654-ced7-11e7-9909-cc8ecfbb6b06.png)

**Comment by NasH5169** [comment]
👍 

Same here :-)

**Comment by NasH5169** [comment]
Found :-)

Miss these lines for the UIReader document:

[readerDocument setUseNativeRendering];
[readerDocument setHighlightLinks:NO];
[readerDocument setShowRTL:NO];

(Don't have time to check the line linked to this issue)

**Comment by lukaspacha** [comment]
Hi @NasH5169 - just tested, works for me too. Thanks!
