### ISSUE TITLE
Port to AppKit

### ISSUE THREAD

**Issue by dehlen** [vfr/UXReader-iOS#18]
Hi @vfr,

I am wondering what would be necessary to provide a OSX compatible framework. Pdfium can be build for OSX and as far as I can see one would need to rewrite the UI handling from scratch. This means replacing UIKit with AppKit and therefore rewrite most of the views since UIKit works quite differently with UIView and UIViewController from what would be considered good API with AppKit and NSWindows/NSViewControllers/NSViews.

Are there any ambitions to make this repository compatible for cocoa applications or is this something which is out of scope ?

Best Regards,
David

**Comment by vfr** [comment]
Actually the macOS AppKit version was developed before the iOS UIKit version of the UXReader framework. With the work Apple has done on PDFKit and its inclusion in iOS 11 and the narrowing of the focus of the PDFium library by Google/Foxit as mainly a Chromium feature, work on the UXReader framework has stopped. If I get a chance I'll make the macOS and the Windows Desktop API versions available as they are on GitHub.

**Comment by dehlen** [comment]
That would be awesome I would love to see this happen. Also if I can support this don‘t hesitate to ask.  I am happy to help :)

**Comment by paulocoutinhox** [comment]
Hi,

You can get all here:
https://github.com/paulo-coutinho/pdfium-lib

Thanks.
