### ISSUE TITLE
libpdfium.a missing required architecture x86_64

### ISSUE THREAD

**Issue by fborelli** [vfr/UXReader-iOS#2]
Hello Julius!

Thanks for sharing this new project! I could not compile and run in the simulator.

Ld: warning: ignoring file /xxxx/xxxxxx/xxxxxx/UXReader-iOS-master/UXReader/UXReader/PDFium/libpdfium.a, missing required architecture x86_64 in file // xxxx / xxxxxx / xxxxxx / UXReader-iOS-master / UXReader /UXReader/PDFium/libpdfium.a (2 slices)

Using the command: lipo -info libpdfium.a

I get the response: Architectures in the fat file: libpdfium.a are: armv7 arm64

When compiling and running on the device it is freezing after opening a document.

**Comment by vfr** [comment]
> x86_64

I've not been able to get PDFium to build for the simulator. Please head over to the PDFium project site and file a bug report asking for better iOS support...

> freezing on device

I've not seen that here. If you could debug this and figure out why, that would be great.

**Comment by fborelli** [comment]
X86_64
There are already some similar requests in the pdfium forum. For those interested, I think it is worth find a solution.
https://groups.google.com/forum/#!forum/pdfium

Freezing on device
I believe the slowness was caused by the file download process. Using a file already downloaded works perfectly. I really enjoyed the navigation between the search results and the possibility of displaying more than one page at a time.

**Comment by vfr** [comment]
> I believe the slowness was caused by the file download process

Remote document viewing (http://.../file.pdf) is strictly experimental. PDFium is not thread-safe so all document processing and thus document data download (no local caching either) has to happen on the main UI thread.

> There are already some similar requests in the pdfium forum

Please add your voice to the requests. We need iOS developers to speak up to get them going on iOS better support...
