### ISSUE TITLE
PDFium compiling to iOS

### ISSUE THREAD

**Issue by prsolucoes** [vfr/UXReader-iOS#21]
Hi,

I finished my script to build the PDFium to iOS. All is here with manual patchs:
https://github.com/prsolucoes/mobile-pdfium

But i have some issues after compile. All issues is described here:
https://github.com/prsolucoes/mobile-pdfium/issues/1

Can you help me?

**Comment by Changzw** [comment]
this issue https://github.com/prsolucoes/mobile-pdfium/issues/1

**Comment by paulocoutinhox** [comment]
Hi,

It is working. If anyone wanna, it is building on travis and all instructions is here:
https://github.com/prsolucoes/mobile-pdfium

Thanks.
