### ISSUE TITLE
not found Todo.txt

### ISSUE THREAD

**Issue by Baleen-Y** [vfr/UXReader-iOS#23]
hi
not found Todo.txt

**Comment by iDevelopper** [comment]
Which Todo.txt?

**Comment by Baleen-Y** [comment]
> Which Todo.txt?
Thank your reply
![image](https://user-images.githubusercontent.com/21964147/47075733-b8c4c800-d22f-11e8-894e-c680c29201ef.png)
Red line position in the picture
But it is not important anymore.
