### ISSUE TITLE
Mobile pdfium project 

### ISSUE THREAD

**Issue by paulocoutinhox** [vfr/UXReader-iOS#29]
Hello,

Im Paulo from mobile pdfium project on github.

I want your help to make it work with success on iOS. I made all changes to make it build correctly. 

But the final library is not with all symbols and i don't know why. 

Can you help me?

https://github.com/prsolucoes/mobile-pdfium/issues/4

The travis CI is compiling it with success too. Can be a way to check it.

Thanks for any help you can provide :)

Any help will be nice for the community.

**Comment by vfr** [comment]
libpdfium.a appears to be too small (7.5 MB).

Are you properly combining all of the .o files into the library .a file?

**Comment by paulocoutinhox** [comment]
Hi,

You are correct. I have added now all symbols. But some symbols appear on `nm -C` command, but still happen error as not found.

![image](https://user-images.githubusercontent.com/395096/69100717-855cfa00-0a3c-11ea-87bd-2d3162dedf0b.png)

But when i run `nm -C build/ios/release/libpdfium.a | grep CRYPT_MD5Generate` i got:

```
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
                 U CRYPT_MD5Generate(unsigned char const*, unsigned int, unsigned char*)
                 U CRYPT_MD5Generate(unsigned char const*, unsigned int, unsigned char*)
                 U CRYPT_MD5Generate(unsigned char const*, unsigned int, unsigned char*)
```

What can be wrong?

**Comment by paulocoutinhox** [comment]
Hi,

Some .o files are not merged. I will do it and will make a new release.

Any problems i back here :)

Thanks.

**Comment by paulocoutinhox** [comment]
Yes, I already fixed it. It is working on device now.

The only problem now is on simulator. After load pdf document it crash, but on device works.

Can you help me with it?

**Comment by paulocoutinhox** [comment]
Hi,

I make a project to build pdfium master branch for iOS.

It is working fine for arm, arm64 and macos.

There is only one problem on ios simulator (os=ios and cpu=x64).

I post the issue on project here:
https://github.com/prsolucoes/mobile-pdfium/issues/5

Can anyone help me solve this pls.

Thanks.

**Comment by paulocoutinhox** [comment]
Hi,

Problems solved. I have reimplemented read string methods from two files to solve memory bugs:
- https://github.com/prsolucoes/mobile-pdfium/blob/master/patchs/cpdf_streamparser_modified.cpp
- https://github.com/prsolucoes/mobile-pdfium/blob/master/patchs/cpdf_syntax_parser_modified.cpp

Now it is working very well on all devices.

Thanks.
