### ISSUE TITLE
ld: library not found for -lpdfium

### ISSUE THREAD

**Issue by mabdelwahab** [vfr/UXReader-iOS#3]
Hello,

I downloaded the git compressed file of your project, attached a device and tried to run the reader project but I faced the following issue : 

ld: library not found for -lpdfium
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help

**Comment by vfr** [comment]
https://github.com/vfr/UXReader-iOS/blob/master/HOWTO.md

**Comment by mabdelwahab** [comment]
Well, I read the file several times before, but didn't notice the release ZIP file.
Anyways, thank you. I will close this issue.
